<?php
/** Database Credentials generated by Installer */
declare(strict_types=1);

define('DB_HOST', '127.0.0.1');
define('DB_PORT', '3306');
define('DB_NAME', 'game_platform');
define('DB_USER', 'game_user');
define('DB_PASS', 'GamePass123!#');
define('DB_CHARSET', 'utf8mb4');
